### ISSUE TITLE
Spinning Carousel Animation

### ISSUE THREAD

**Issue by Tanisha-Puri** [opencodeiiita/Vision-2.0#1]
**OPEN TO ALL** 

**No need to claim this issue** 

**NO SUBMISSION WILL BE ACCEPTED AFTER  17th December 11:59 P.M.**

*Hey Creators!*
In this task, you are required to design a Spinning Carousel Animation in Figma. A carousel is a rotating set of elements (like images or cards) that can showcase multiple items in a visually appealing and interactive manner. Your goal is to create a smooth and visually striking spinning animation.
You can refer the following video for your reference:
https://youtu.be/s2ro7Lom0OY?si=0-em5CL0dNJm-kin

### **Submission Guideline:**
1. Submit the link to your Figma file in a .txt file.
2. Place the .txt file under the "Spinning Carousel Animation" folder in this repository.
3. Ensure the animation is well-structured and polished.
This task is for ***20 points*.**

### **MDC (Minimum Design Criteria):**
1. The carousel should rotate smoothly with a seamless animation effect.
2. The spinning animation must appear professional and visually appealing.
3. Avoid directly copying from the reference video; make it your own!

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by Tanisha-Puri** [comment]
@PriyamJChakrabarty 
No need to claim this issue. It's OPEN TO ALL.

**Comment by PriyamJChakrabarty** [comment]
Yes Didn't check, sry :)

**Comment by Tanisha-Puri** [comment]
Completed
