### ISSUE TITLE
Bouncing Ball Animation

### ISSUE THREAD

**Issue by Tanisha-Puri** [opencodeiiita/Vision-2.0#29]
### Create a bouncing Ball Animation 
🌟 **OPEN TO ALL** 🌟  
 ⚠️ **No need to claim this issue**  
⏳ **NO SUBMISSION WILL BE ACCEPTED AFTER 20th December 11:59 A.M.**  

## 🎨 **Hey Creators!**  
In this task, you are required to design a **Bouncing Ball Animation** in **Figma**.  

The goal is to simulate the **natural motion** of a ball bouncing with smooth and visually appealing animation effects. Focus on capturing realistic physics like:  
- **Gravity**  
- **Bounce height**  
- **Easing transitions**  

🎥 **Reference for inspiration:**  
https://youtu.be/3m0NHZz7ncI?si=bncoLs4NN4_is9wq 

---

### 📌 **Submission Guidelines:**  
1. Submit the link to your **Figma file** in a `.txt` file.  
2. Place the `.txt` file under the `Bouncing Ball Animation` folder in this repository.  
3. Ensure your animation is **clean**, **structured**, and **polished**.  
4. Avoid directly copying from the reference. Make it **your own creation**!  

🔖 **This task is worth: _20 points_**  

---

### ✅ **MDC (Minimum Design Criteria):**  
1. The ball must bounce with **smooth and realistic motion** (easing effects encouraged).  
2. Show **multiple bounces** with decreasing height to simulate **natural physics**.  
3. Add a visually appealing **background** or subtle design elements to enhance the animation.  
4. Ensure the animation **loops seamlessly**.  

---

### 💬 **Need Help?**  
If you have any doubts regarding the task or submission process, ping us on **Discord**.  
We’ll be happy to help! 😊  

---

✨ **Happy Designing!** ✨

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by Tanisha-Puri** [comment]
No need to claim for open for all issue.

**Comment by Tanisha-Puri** [comment]
Completed
