### ISSUE TITLE
Good Design Bad Design 1

### ISSUE THREAD

**Issue by Tanisha-Puri** [opencodeiiita/Vision-2.0#86]
# Good Design Bad Design 01  
**OPEN TO ALL**  
**NO NEED TO CLAIM THE ISSUE**  
**THIS IS A COMPETITIVE ISSUE**  
**NO SUBMISSION WILL BE ACCEPTED AFTER 24th December, 11:59 P.M.**  

## Hola Designers! 🎨  

In this task, you are required to **redesign badly designed app screens** in **Figma** to create an improved version with a **Good UI** and also **write clearly in points why the original design is bad and what changes you have made to improve it.**
Good UI design makes the app more visually appealing and provides a friendly **User Experience (UX)**.  

This is a **competitive issue**, and your Pull Requests (PRs) will be closed **after everyone has submitted** within the given timeframe.  

### **Important Notes:**  
- **Plagiarism is not allowed.**  
  Plagiarism will result in **no points** being awarded for the issue along with **20 points deduction** from your leaderboard points.  
- **Be original, creative, and thoughtful** in your design!  

## **Submission Guidelines:**  
1. Submit the **link to your Figma file** in a `.txt` file under the folder:  
   `Good Design Bad Design 1`.  
2. In the same `.txt` file, include a **pointwise explanation** of:  
   - Why the original design is bad.  
   - The changes you made.  
   - How your changes improve the **UI** and provide a better **UX**.  
   _(Avoid writing big paragraphs; use clear points.)_  

## **Scoring Criteria:**  
- **50 points**: Best UI Design  
- **40 points**: 2nd Best  
- **30 points**: 3rd Best  

## **MDC (Minimum Design Criteria):**  
To qualify for full points, ensure your design meets the following criteria:  
1. **Appropriate, consistent, and clean design.**  
2. Redesign **all three screens** provided.    
3. You can:  
   - Change the **shape, size, and positioning** of elements.  
   - Change the **color scheme**
   - Change the **button colors** (but follow the original color theory).  
   - **Remove or add features** if you think they improve functionality.  
5. Redesign the app with a focus on **better functionality and improved usability**.  

## **For Queries**  
For any doubts related to the task or submission process, feel free to **ping us on Discord**. We’ll be happy to help! 😊  

![Screenshot 2024-12-22 084206](https://github.com/user-attachments/assets/d60d24e0-2ac7-4bf9-b8fc-9fbd198d904d)
![Screenshot 2024-12-22 084221](https://github.com/user-attachments/assets/e8ebbc3e-c8a3-441d-a188-9b1c46a0e59d)
![Screenshot 2024-12-22 084247](https://github.com/user-attachments/assets/71ef889b-55ad-4fa1-b06a-24855c35e8f2)

**Comment by shrut2606** [comment]
claim
